/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tourism;

import cartograph.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author roberto
 * @author cristian
 * @author alvaro
 * @author hui
 * 
 */
public class Principal {
    
    private Mapa mapa = new Mapa("../images/europe.png");


    
    public void test() {
        Cruce c1 = new Cruce (25,665, "Lisboa");
        Cruce c2 = new Cruce (140,670, "Madrid");
        Cruce c3 = new Cruce (235,655, "Barcelona");
        Cruce c4 = new Cruce (270,500, "París");
        Cruce c5 = new Cruce (240,430, "Londres");
        Cruce c6 = new Cruce (155,380, "Dublín");
        Cruce c7 = new Cruce (60,100, "Reikiavik");
        Cruce c8 = new Cruce (170,350, "Belfast");
        Cruce c9 = new Cruce (215,325, "Edimburgo");
        Cruce c10 = new Cruce (425,630, "Roma");
        Cruce c11 = new Cruce (750,280, "Moscú");

        this.mapa.addCruce(c1);
        this.mapa.addCruce(c2);
        this.mapa.addCruce(c3);
        this.mapa.addCruce(c4);
        this.mapa.addCruce(c5);
        this.mapa.addCruce(c6);
        this.mapa.addCruce(c7);
        this.mapa.addCruce(c8);
        this.mapa.addCruce(c9);
        this.mapa.addCruce(c10);
        this.mapa.addCruce(c11);
              
        ArrayList<Cruce> prueba = new ArrayList<Cruce>();
        
        prueba.add(c1);
        
        mapa.ruta = new Ruta(prueba);
        
        int cantidad = 50;
        mapa.almacen = new Hotel(prueba.get(0).getX(),prueba.get(0).getY(),cantidad,"../images/almacen.png");
        
        Avion camion = new Avion("../images/airplane.png");
        
        mapa.addTransporte(camion);
        
        try {
            mapa.ruta.calcular();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ruta no encontrada");
        }
        //r.draw(this.mapa);
        
        mapa.transporte.drive(mapa);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void main(String args[]) {
        Principal p = new Principal();
        p.test();
        
    }
}
